version: '3'

services:
  db: 
    image: 'mongo'
    # volume: 
    #   - ./db/:data/

  webapp:
    build: .
    command: /usr/local/bin/python -m pip install --upgrade pip ;pip install virtualenv; python3 venv Venv; source Venv/bin/activate; python /usr/code/manage.py migrate --noinput; python /usr/code/manage.py runserver
    volumes:
      - .:/usr/code/
    # port: 
    #   - "3000:3000"
    depends_on:
        - db
